<?php

namespace PaperManageBundle\Entity;

/**
 * PaperRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaperRepository extends \Doctrine\ORM\EntityRepository
{
	//添加/编辑(单个)题型(编辑的操作和添加相似)
    public function add($paper) {
    	$em = $this->getEntityManager();
        $em->persist($paper);
        $em->flush();
        return true;
    }

	//删除单个题型信息
    public function delete($id) {
    	$em = $this->getEntityManager();
        $paper=$this->findOneById($id);
        $em->remove($paper);
        $em->flush();
        return true;
    }

    //批量删除题型信息
    public function multiDelete($ids) {
    	foreach( $ids as $id ) {
    		$this->delete($id);
    	}
    	return true;
    }
}
