<?php

namespace PaperManageBundle\Entity;

/**
 * QuestionTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
