<?php

namespace PaperManageBundle\Entity;

/**
 * QuestionBankRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionBankRepository extends \Doctrine\ORM\EntityRepository
{
}
