<?php

namespace GE\ExaminationManageBundle\Entity;

/**
 * ExaminationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExaminationRepository extends \Doctrine\ORM\EntityRepository
{
}
