<?php

namespace GE\ExaminationManageBundle\Entity;

/**
 * ExaminationBatchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExaminationBatchRepository extends \Doctrine\ORM\EntityRepository
{
}
