paper_manage:
    resource: "@PaperManageBundle/Controller/"
    type:     annotation
    prefix:   /

examination_manage:
    resource: "@ExaminationManageBundle/Controller/"
    type:     annotation
    prefix:   /

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

app: 
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

system_manage:
    resource: "@SystemManageBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"