ge_examination_manage:
    resource: "@GEExaminationManageBundle/Controller/"
    type:     annotation
    prefix:   /

ge_user:
    resource: "@GEUserBundle/Controller/"
    type:     annotation
    prefix:   /

ge_system_manage:
    resource: "@GESystemManageBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /admin

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

registration:
    path: /register
    defaults: { _controller: FOSUserBundle:Registration:register}