examination_manage:
    resource: "@ExaminationManageBundle/Controller/"
    type:     annotation
    prefix:   /

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

app: 
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

system_manage:
    resource: "@SystemManageBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /admin

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

registration:
    path: /register
    defaults: { _controller: FOSUserBundle:Registration:register}