manage_bundle_system_management_bundle_academy:
    resource: "@ManageBundleSystemManagementBundleAcademyBundle/Controller/"
    type:     annotation
    prefix:   /

manage_bundle_system_management_bundle_grade_information:
    resource: "@ManageBundleSystemManagementBundleGradeInformationBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
