# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha1

    role_hierarchy:
        ROLE_ADMIN:             ROLE_USER

    providers:
        admin:
            id:                 fos_user.user_provider.username

    firewalls:
        dev:
            pattern:            ^/(_(profiler|wdt)|css|images|js)/
            security:           false

        admin:
            pattern:            ^/
            form_login:
                login_path:     @Login
                check_path:     fos_user_security_check
            logout:
                path:            fos_user_security_logout
                target:          
            anonymous:           true

    role_hierarchy:
        ROLE_ADMIN:          ROLE_USER
        ROLE_POST:           ROLE_ADMIN
        ROLE_CATEGORY:       ROLE_ADMIN
        ROLE_SUPER_ADMIN:    [ROLE_POST, ROLE_CATEGORY]

    access_control:
        - { path: ^/admin/login,    roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/user,     roles: ROLE_SUPER_ADMIN }
        - { path: ^/admin/,         roles: ROLE_ADMIN }