# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha1

    providers:
        fos_user:
            id:                 fos_user.user_provider.username

    firewalls:
        dev:
            pattern:            ^/(_(profiler|wdt)|css|images|js)/
            security:           false

        main:
            pattern:            ^/
            form_login:
                provider: fos_user
                csrf_provider: form.csrf_provider
                login_path: @BackendLogin
            logout:       true
            anonymous:           ~

    role_hierarchy:
        ROLE_MONITOR:          ROLE_MONITOR
        ROLE_TEACHER:           ROLE_TEACHER
        ROLE_SECRETARY:       ROLE_SECRETARY
        ROLE_SYSTEM_MANAGER:    ROLE_SYSTEM_MANAGER


    access_control:
       - { path: ^/manage, role: ROLE_SYSTEM_MANAGER }
