<?php

namespace UserBundle\Entity;

/**
 * StudentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentRepository extends \Doctrine\ORM\EntityRepository
{
	//添加/编辑单个学生(编辑学生时的操作和添加学生相似)
    public function add($Student) {
    	$em = $this->getEntityStudent();
        $em->persist($Student);
        $em->flush();
    }

	//删除单个学生
    public function delete($id) {
    	$em = $this->getEntityStudent();
        $Student=$this->findOneById($id);
        $em->remove($Student);
        $em->flush();
        return 1;
    }

    //批量删除学生
    public function multiDelete($ids) {
    	foreach( $ids as $id ) {
    		$this->delete($id);
    	}
    	return 1;
    }
}
