<?php

namespace GE\UserBundle\Entity;

/**
 * ManagerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ManagerRepository extends \Doctrine\ORM\EntityRepository
{
	//添加单个管理者
    public function add($manager) {
    	$em = $this->getEntityManager();
        $em->persist($manager);
        $em->flush();
    }

	//删除单个管理者
    public function delete($id) {
    	$em = $this->getEntityManager();
        $manager=$this->findOneById($id);
        $em->remove($manager);
        $em->flush();
    }

    //批量删除管理者
    public function multiDelete($ids) {
    	foreach( $ids as $id ) {
    		$this->delete($id);
    	}
    }
}
