<?php

namespace SystemManageBundle\Entity;

use Doctrine\ORM\EntityRepository;
/**
 * AcademyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AcademyRepository extends \Doctrine\ORM\EntityRepository
{
	//添加/编辑(单个)学院(编辑的操作和添加相似)
    public function add($academy) {
    	$em = $this->getEntityManager();
        $em->persist($academy);
        $em->flush();
        return true;
    }

	//删除单个学院信息
    public function delete($id) {
    	$em = $this->getEntityManager();
        $academy=$this->findOneById($id);
        $em->remove($academy);
        $em->flush();
        return true;
    }

    //批量删除学院信息
    public function multiDelete($ids) {
    	foreach( $ids as $id ) {
    		$this->delete($id);
    	}
    	return true;
    }
}
