<?php

namespace SystemManageBundle\Entity;

use Doctrine\ORM\EntityRepository;
/**
 * ExaminationRoomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExaminationRoomRepository extends \Doctrine\ORM\EntityRepository
{
	//添加/编辑(单个)考场(编辑的操作和添加相似)
    public function add($examinationroom) {
        $em = $this->getEntityManager();
        $em->persist($examinationroom);
        $em->flush();
    }

    //删除单个考场信息
    public function delete($id) {
        $em = $this->getEntityManager();
        $examinationroom=$this->findOneById($id);
        $em->remove($examinationroom);
        $em->flush();
        return true;
    }

    //批量删除考场信息
    public function multiDelete($ids) {
        foreach( $ids as $id ) {
            $this->delete($id);
        }
        return true;
    }
}
