<?php

namespace SystemManageBundle\Entity;

use Doctrine\ORM\EntityRepository;
/**
 * GradeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GradeRepository extends \Doctrine\ORM\EntityRepository
{
	//添加/编辑(单个)年级(编辑的操作和添加相似)
    public function add($grade) {
    	$em = $this->getEntityManager();
        $em->persist($grade);
        $em->flush();
        return true;
    }

	//删除单个管理者
    public function delete($id) {
    	$em = $this->getEntityManager();
        $grade=$this->findOneById($id);
        $em->remove($grade);
        $em->flush();
        return true;
    }

    //批量删除管理者
    public function multiDelete($ids) {
    	foreach( $ids as $id ) {
    		$this->delete($id);
    	}
    	return true;
    }
}

