<?php

namespace ManageBundle\SystemManagementBundle\AcademyBundle\Entity;

/**
 * AcademyInfomationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AcademyInfomationRepository extends \Doctrine\ORM\EntityRepository
{
}
