<?php

namespace GE\SystemManageBundle\Entity;

use Doctrine\ORM\EntityRepository;
/**
 * AcademyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AcademyRepository extends \Doctrine\ORM\EntityRepository
{
	public function delete($id)
    {
        $academy = $this-> find($id);  
        $this->getEntityManager()->remove($academy);
        $this->getEntityManager()->flush();
    }	
}
