<?php

namespace GE\SystemManageBundle\Entity;

/**
 * AcademyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AcademyRepository extends \Doctrine\ORM\EntityRepository
{
}
