<?php

namespace GE\SystemManageBundle\Entity;

/**
 * ExaminationRoomInfomationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExaminationRoomInfomationRepository extends \Doctrine\ORM\EntityRepository
{
}

