<?php

namespace GE\SystemManageBundle\Entity;

/**
 * ExaminationRoomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExaminationRoomRepository extends \Doctrine\ORM\EntityRepository
{
}

