<?php

namespace GE\SystemManageBundle\Entity;

use Doctrine\ORM\EntityRepository;
/**
 * GradeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GradeRepository extends \Doctrine\ORM\EntityRepository
{
	public function delete($id)
    {
        $grade = $this-> find($id);  
        $this->getEntityManager()->remove($grade);
        $this->getEntityManager()->flush();
    }	
}

