<?php

namespace GE\SystemManageBundle\Entity;
/**
 * GradeInformationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GradeInformationRepository extends \Doctrine\ORM\EntityRepository
{
}

